import axios from 'axios'
import type { AttendanceRecord, AuthResponse, Location, LocationRequest, LoginRequest, Notification, RegisterRequest, SosRequest } from '../types/auth'
const api = axios.create({ baseURL: import.meta.env.VITE_API_URL ?? 'http://localhost:8080/api/v1', headers: { 'Content-Type': 'application/json' } })
api.interceptors.request.use((config) => { const token = localStorage.getItem('tracksphere.accessToken'); if (token) config.headers.Authorization = `Bearer ${token}`; return config })
api.interceptors.response.use(response => response, async (error) => { const request = error.config; if (error.response?.status !== 401 || request?._retried || !localStorage.getItem('tracksphere.refreshToken')) return Promise.reject(error); request._retried = true; try { const { data } = await axios.post<AuthResponse>(`${api.defaults.baseURL}/auth/refresh`, { refreshToken: localStorage.getItem('tracksphere.refreshToken') }); localStorage.setItem('tracksphere.accessToken', data.accessToken); localStorage.setItem('tracksphere.refreshToken', data.refreshToken); localStorage.setItem('tracksphere.user', JSON.stringify(data.user)); request.headers.Authorization = `Bearer ${data.accessToken}`; return api(request); } catch { localStorage.clear(); window.location.assign('/login'); return Promise.reject(error); } })
export const authApi = { login: (data: LoginRequest) => api.post<AuthResponse>('/auth/login', data).then(r => r.data), register: (data: RegisterRequest) => api.post<AuthResponse>('/auth/register', data).then(r => r.data), me: () => api.get('/users/me').then(r => r.data) }
export const locationApi = { live: () => api.get<Location[]>('/locations/live').then(r => r.data), history: (vehicleId: string) => api.get<Location[]>(`/locations/${vehicleId}/history`).then(r => r.data), record: (data: LocationRequest) => api.post<Location>('/locations', data).then(r => r.data) }
export const attendanceApi = { clockIn: () => api.post<AttendanceRecord>('/attendance/clock-in').then(r => r.data), clockOut: () => api.post<AttendanceRecord>('/attendance/clock-out').then(r => r.data), today: () => api.get<AttendanceRecord | null>('/attendance/today').then(r => r.data), report: (search = '') => api.get<AttendanceRecord[]>('/attendance/report', { params: { search } }).then(r => r.data) }
export const safetyApi = { notifications: () => api.get<Notification[]>('/notifications').then(r => r.data), sos: (data: SosRequest) => api.post('/sos', data).then(r => r.data) }
export default api
