import { createContext, useCallback, useContext, useMemo, useState } from 'react'
import type { PropsWithChildren } from 'react'
import { authApi } from '../services/api'
import type { LoginRequest, RegisterRequest, User } from '../types/auth'
type AuthState = { user: User | null; loading: boolean; login: (data: LoginRequest) => Promise<void>; register: (data: RegisterRequest) => Promise<void>; logout: () => void }
const AuthContext = createContext<AuthState | undefined>(undefined)
const storedUser = () => { try { return JSON.parse(localStorage.getItem('tracksphere.user') ?? 'null') as User | null } catch { return null } }
export function AuthProvider({ children }: PropsWithChildren) { const [user, setUser] = useState<User | null>(storedUser); const [loading, setLoading] = useState(false); const persist = useCallback((response: { accessToken: string; refreshToken: string; user: User }) => { localStorage.setItem('tracksphere.accessToken', response.accessToken); localStorage.setItem('tracksphere.refreshToken', response.refreshToken); localStorage.setItem('tracksphere.user', JSON.stringify(response.user)); setUser(response.user) }, []); const login = async (data: LoginRequest) => { setLoading(true); try { persist(await authApi.login(data)) } finally { setLoading(false) } }; const register = async (data: RegisterRequest) => { setLoading(true); try { persist(await authApi.register(data)) } finally { setLoading(false) } }; const logout = () => { localStorage.removeItem('tracksphere.accessToken'); localStorage.removeItem('tracksphere.refreshToken'); localStorage.removeItem('tracksphere.user'); setUser(null) }; const value = useMemo(() => ({ user, loading, login, register, logout }), [user, loading, login, register, logout]); return <AuthContext.Provider value={value}>{children}</AuthContext.Provider> }
export const useAuth = () => { const context = useContext(AuthContext); if (!context) throw new Error('useAuth must be used within AuthProvider'); return context }
